### ISSUE TITLE
First DonutSection 

### ISSUE THREAD

**Issue by va-utils** [futuredapp/donut#61] opened 2020-12-22 20:22 UTC
The first section always occupies more, another section of similar amount. Can I change that somehow? Thank you earlier.

**Comment by matejsemancik** [comment] 2020-12-22 20:52
Hi, If I understand correctly, the appearance you are describing is caused by rounded stroke cap of DonutSection line when set to `DonutStrokeCap.ROUND`. We currently do not account for stroke cap width when displaying sections, so -- right now, unfortunately no, you cannot change that. We can look into that in future releases.

**Comment by va-utils** [comment] 2020-12-23 15:09
Thanks

**Comment by matejsemancik** [comment] 2024-10-13 14:04
This behavior was fixed in https://github.com/futuredapp/donut/pull/103

**Closed by matejsemancik** 2024-10-13 14:04 UTC
Labels: Type: Enhancement
